[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jot"
version = "0.1.0"
description = "Minimal cross-platform Python CLI for journaling with persistent file path"
requires-python = ">=3.8"
dependencies = [
    "rich>=13.0"
]

[project.scripts]
jot = "jot:main"
